### ISSUE TITLE
GhostscriptAPICallException: An error occured when call to 'gsapi_new_instance' is made: -100

### ISSUE THREAD

**Issue by mehdymohajery** [jhabjan/Ghostscript.NET#10]
I occasionally get this exception, any idea about the root cause?

GhostscriptAPICallException: An error occured when call to 'gsapi_new_instance' is made: -100,

stack trace:
Ghostscript.NET.Interpreter.GhostscriptInterpreter.Initialize():47
 Ghostscript.NET.Interpreter.GhostscriptInterpreter..ctor(GhostscriptVersionInfo version, Boolean fromMemory):55
 Ghostscript.NET.Viewer.GhostscriptViewer.Open(String path, GhostscriptVersionInfo versionInfo, Boolean dllFromMemory):47
 Ghostscript.NET.Viewer.GhostscriptViewer.Open(Stream stream, GhostscriptVersionInfo versionInfo, Boolean dllFromMemory):47
 Ghostscript.NET.Rasterizer.GhostscriptRasterizer.Open(Stream stream, GhostscriptVersionInfo versionInfo, Boolean dllFromMemory):36

**Comment by EricSmekens** [comment]
I have the same error, when I call StartProcessing.

**Comment by mehdymohajery** [comment]
Fixed the issue by changing
 _rasterizer.Open(mm, lastInstalledVersion, false);
to
 _rasterizer.Open(mm, lastInstalledVersion, true);

**Comment by JenkaJmenka** [comment]
I'm sorry for my question
I have the same error. 
Any ideas how it can be solved?

**Comment by jhabjan** [comment]
Error -100 means that you are passing some bad parameters or you can try mehdymohajery solutoin.

**Comment by dherbe** [comment]
I also got this error and It really wasn't because of bad arguments.
mehdymohajery suggestion worked perfectly.
thanks

**Comment by csharpner** [comment]
@mehdymohajery what is this lastInstalledVersion?  Where/how do I get it?

**Comment by cpayne22** [comment]
@csharpner  this worked for me:

`GhostscriptVersionInfo gsVersionInfo = GhostscriptVersionInfo.GetLastInstalledVersion(GhostscriptLicense.GPL | GhostscriptLicense.AFPL, GhostscriptLicense.GPL);`

Source:  [https://stackoverflow.com/q/26917330/5188](https://stackoverflow.com/q/26917330/5188)

**Comment by bkwdesign** [comment]
I'm still getting this error and none of the solutions posted above worked. I just finished running the .exe to install Ghostscript to my Windows 10 workstation on C:/Ghostscript

I can see my "last version info" is being detected successfully when I debug:
![image](https://user-images.githubusercontent.com/3177513/97358038-08074f80-1871-11eb-8808-57f66972daf9.png)

Here's my code snippet that is failing:
```csharp
    int desired_x_dpi = 96;
    int desired_y_dpi = 96;

   string inputPdfPath = "sample.pdf";

   using (var rasterizer = new GhostscriptRasterizer())
   {
        GhostscriptVersionInfo gsVersionInfo = GhostscriptVersionInfo.GetLastInstalledVersion(GhostscriptLicense.GPL | GhostscriptLicense.AFPL, GhostscriptLicense.GPL);

        byte[] buffer = File.ReadAllBytes(inputPdfPath);
        MemoryStream ms = new MemoryStream(buffer);
               
        rasterizer.Open(ms, gsVersionInfo, true);
   }
```

**Comment by Amonra69** [comment]
Same issue, Solution of @mehdyh  doesn't work. I try to setup dll manually but it doesn't work again

```
            int desired_x_dpi = 96;
            int desired_y_dpi = 96;

            string inputPdfPath = @"C:\image.pdf";
            string outputPath = @"C:\";

            var _lastInstalledVersion = new GhostscriptVersionInfo(Version.Parse("9.53.3"), @"C:\Program Files (x86)\gs\gs9.53.3\bin\gsdll32.dll", @"C:\Program Files (x86)\gs\gs9.53.3\lib\gsdll32.lib", GhostscriptLicense.GPL);

            using (var _rasterizer = new GhostscriptRasterizer())
            {
                

                //MemoryStream usage sample


                byte[] buffer = File.ReadAllBytes(inputPdfPath);
                MemoryStream ms = new MemoryStream(buffer);
   


                _rasterizer.Open(inputPdfPath, _lastInstalledVersion, true);

                for (int pageNumber = 1; pageNumber <= _rasterizer.PageCount; pageNumber++)
                {
                    string pageFilePath = Path.Combine(outputPath, "Page-" + pageNumber.ToString() + ".png");

                    Image img = _rasterizer.GetPage(desired_x_dpi, desired_y_dpi, pageNumber);
                    img.Save(pageFilePath, ImageFormat.Png);

                    Console.WriteLine(pageFilePath);
                }
            }
```

**Comment by bkwdesign** [comment]
@Amonra69 - I finally [figured out](https://stackoverflow.com/a/56230513/1520850) that I need to roll back to [GS 9.26](https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs926/gs926aw64.exe) before the .NET wrapper works correctly

**Comment by Amonra69** [comment]
> @Amonra69 - I finally [figured out](https://stackoverflow.com/a/56230513/1520850) that I need to roll back to [GS 9.26](https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs926/gs926aw64.exe) before the .NET wrapper works correctly

you save my time
thank you

**Comment by brothers-morrison** [comment]
note:
this did NOT fix it for me
@Amonra69 - (https://stackoverflow.com/a/56230513/1520850) [you] need to roll back to [GS 9.26](https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs926/gs926aw64.exe) before the .NET wrapper works correctly

Trying to use Ghostscript.NET out of the box with the following
switches: -sDEVICE=mswinpr2 -dNoCancel=true -dQueryUser=3 -dPrinted -dBATCH -dNOPAUSE -dNOPROMPT -dNOSAFER -dNumCopies=1 -sOutputFile="%printer%\\network_installed\printer1" "\\network_fileshare\LS-F123.pdf"
