### ISSUE TITLE
viewer.Dpi not available in nuget 1.2.0 version

### ISSUE THREAD

**Issue by harpactus** [jhabjan/Ghostscript.NET#12]
Hi,

I've just discovered this great package and installed version 1.2.0 from Nuget.  I see that the .Dpi property of the viewer object isn't available in Visual Studio (property does not exist).  However, this property is available in the source code.
I've solved the problem in replacing the Ghostscript.NET.dll nuget version by the version downloaded here but it's just a workaround.

yvan

Visual Studio 2013 express / .NET 4.5 / Ghostscript 64bits 9.6 / VB.NET

**Comment by jhabjan** [comment]
Fixed in v.1.2.1
