### ISSUE TITLE
Print pdf to printer from Web Service

### ISSUE THREAD

**Issue by RobFra** [jhabjan/Ghostscript.NET#13]
Hello, 
I'm trying to print a pdf file to printer directly from a Web service.
It works under IIS Express but in deployment machine it doesn't work. 
Gives:
An error occured when call to 'gsapi_new_instance' is made: -100

The code is:

```
Using processor As New GhostscriptProcessor()
            Dim switches As New List(Of String)()
            switches.Add("-empty")
            switches.Add("-dPrinted")
            switches.Add("-dBATCH")
            switches.Add("-dNOPAUSE")
            switches.Add("-dNOSAFER")
            switches.Add("-dNumCopies=1")
            switches.Add("-sDEVICE=mswinpr2")
            switches.Add(Convert.ToString("-sOutputFile=%printer%") & printerName)
            switches.Add("-f")
            switches.Add(filename)

            processor.StartProcessing(switches.ToArray(), Nothing)
        End Using
```

IIS is running  64 bit.
ApplicationPool has an Administrator user identity.

**Comment by jhabjan** [comment]
It looks like permission issue. Try to change your Application Pool to use a User Identity.

**Comment by RobFra** [comment]
As I've wrote, I've already tried with a user thas has administrator rights.

**Comment by NabilKem** [comment]
Hi, did you find a solution to this error ??

Thanks

**Comment by tarcisiomartins** [comment]
I have the same problem.
