### ISSUE TITLE
pdf files with mixed portrait and landscape pages

### ISSUE THREAD

**Issue by yongwang** [jhabjan/Ghostscript.NET#16]
I have a pdf file which contains both landscape and portrait images, the landscape images are returned as blank image (portrait pages are fine).

GhostscriptViewerViewEventArgs e  in _view_DisplayOage event, the size of e.image looks ok, but it is an empty image.

did anybody have same issue?

thanks!

**Comment by jhabjan** [comment]
It would be good if you could post that pdf so I can take a look what's wrong.

**Comment by yongwang** [comment]
Thank you Josip, I will email you a sample pdf file.

**Comment by jhabjan** [comment]
Fixed: https://github.com/jhabjan/Ghostscript.NET/commit/01153897800abbbc2870b4e0036dc417ce4d17d5#diff-6d1aaf9fcd883693b9449ae2cd4465c7
