### ISSUE TITLE
An error occured when call to 'gsapi_new_instance' is made: -100 

### ISSUE THREAD

**Issue by sunnydays26** [jhabjan/Ghostscript.NET#19]
HI 

I am developeing an asp.net MVC application intranet application

I want to get the print of pdf document, using the ghostscript dll. It works fine in localhost, but when i run in hosted environment, it throws the error as An error occured when call to 'gsapi_new_instance' is made: -100 .

Is this something related to admin rights?

Thanks
Sunny

**Comment by PleaseTwo** [comment]
I've the same problem.

**Comment by PleaseTwo** [comment]
I've solved my problem. I forgot to call the close method after I finished working with the object GhostscriptRasterizer.
Maybe this will be helpful.

**Comment by andreasblueher** [comment]
I got the same issue running not more than those lines of code using the 64bit ghostscript version:
`using (var processor = new GhostscriptProcessor())
                {
                    var switches = new List<string>
                    {
                        "-empty",
                        "-dPrinted",
                        "-dBATCH",
                        "-dNOPAUSE",
                        "-dNOSAFER",
                        "-dNumCopies=1",
                        "-sDEVICE=mswinpr2",
                        "-dNoCancel",
                        "-sOutputFile=%printer%" + printServer,
                        "-f",
                        pdfFilePath
                    };

                    processor.StartProcessing(switches.ToArray(), null);
                }`
