### ISSUE TITLE
System.Drawing.dll exception occurrs

### ISSUE THREAD

**Issue by jayawantkarale** [jhabjan/Ghostscript.NET#23]
PDF viewer is generated using GhostscriptViewer class.  After closing GhostscriptViewer  object , i display Message on PDF viewer through MessageBox. 
It generates  An unhandled exception of type 'System.ArgumentException' occurred in System.Drawing.dll
Exception and it automatically close the application.
How to handle this situation.

**Comment by jhabjan** [comment]
You you please make me a code example that recreates this problem and send it over?
