### ISSUE TITLE
PDF signature is not within 32 bytes

### ISSUE THREAD

**Issue by erzki** [jhabjan/Ghostscript.NET#29]
I have a file generated in ReportLab that is not threated as a pdf.
The problem is that the signature is not within 32 bytes. In this case it it's 387 bytes but could be more.

The file starts with:
<line>xxxxx xx</line> line
<line>xxxxxxxxxxxxxxxxxxxxxx 22</line> line
<line>xxx xx Stockholm</line> line
<line>Organisationsnummer: xxxxxxxxxxx</line> line
<line>Momsregistreringsnummer: xxxxxxxxxxxxx</line> line
<line>Innehar F-skattebevis</line> line
<line>E-post: <reference refuri="mailto:xxxxxx@xxxxxx.xx">xxxxxx@xxxxxx.xx</reference></line> line
<line/> line
<line/> line
%PDF-1.4

**Comment by jhabjan** [comment]
Thanks. Fixed in v.1.2.1.
