### ISSUE TITLE
Can't open files with specials unicode characters in filename

### ISSUE THREAD

**Issue by euhics** [jhabjan/Ghostscript.NET#3]
If the title has a special character (in my case "ê"), then  : 

GhostscriptRasterizer rasterizer = new GhostscriptRasterizer();
rasterizer.Open(pdfPath, bytearray);

returns "Input string was not in a correct format."

I looked a bit into it and could just see in GhostscriptStdIO -> gs_std_out ->

string output = Marshal.PtrToStringAnsi(pointer, count);

when output should return the list of pages it returns : 
%GSNET_VIEWER_PDF_PAGES: Unrecoverable error: stackunderflow

**Comment by euhics** [comment]
I found a simple workaround for my issue. I copy the file in the user's temp folder with a random name and it works with any pdf (all the problematic ones I tried at least).

string pdfCopyPath = Path.GetTempPath() + Path.GetRandomFileName() + ".pdf";
File.Copy(pdfPath, pdfCopyPath);

**Comment by igorg1234** [comment]
Here is tested solution. Works for me.

http://stackoverflow.com/questions/21251895/using-ghostscript-9-10-in-windows-with-unicode-characters-in-parameters

here is only explanation for 'gsapi_run_string'. -> change all strings under 'gsapi'.
The same approach works for string[] under 'gsapi_init_with_args'.  -> use  IntPtr[] for argv.

Instead '_gs.gsapi_run_string'  use 'call_gsapi_run_string(string str)' provided here.

// ====================================================

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate int gsapi_run_string(IntPtr instance, IntPtr str, Int32 user_errors, out Int32 pexit_code);

// ============================================

public static int call_gsapi_run_string(string str)
{
                  var pArg = StringHelper.NativeUtf8FromString(str);
                  int rc_run;
                    try
                    {
                      rc_run = _gs.gsapi_run_string(_gs_instance, pArg, 0, out exit_code);
                    }
                    finally
                    {
                      StringHelper.releaseManagedPointer(pArg);
                    }
return rc_run;
}

// ===========================================

    public static IntPtr NativeUtf8FromString(string managedString)
    {
      //var buffer = System.Text.Encoding.UTF8.GetBytes(managedString);
      int len = Encoding.UTF8.GetByteCount(managedString);
      byte[] buffer = new byte[len + 1];
      Encoding.UTF8.GetBytes(managedString, 0, managedString.Length, buffer, 0); 
      IntPtr nativeUtf8 = Marshal.AllocHGlobal(buffer.Length);
      Marshal.Copy(buffer, 0, nativeUtf8, buffer.Length);
      return nativeUtf8;
    }

// ===========================================

    public static IntPtr NativeFromString(string managedString)
    {
      return NativeUtf8FromString(managedString);
      //return NativeUtf16FromString(managedString);
    }

// ===========================================

happy coding.
