### ISSUE TITLE
Print big PDF dont work correctly

### ISSUE THREAD

**Issue by dark-cms** [jhabjan/Ghostscript.NET#30]
I use Ghostscript.net to print PDF's from a folder, but it does not work as expected.

If i print a file with 2 Pages, it works fine and the layout is clean and readable.
But if i print a pdf with 73 Pages i got crazy results. 

If i start the Print, ghostscript pops up many times (without -dNoCancel switch) and the layout is sometimes not readable and sometimes with many layout bugs.

What could i do to remove this behavior on big files?

My current Code:

```
private void print(string path)  
        {  
            string defaultPrinter = Configurations.getPrinter();  
            using (GhostscriptProcessor processor = new GhostscriptProcessor())  
            {  
                List<string> switches = new List<string>();  
                switches.Add("-empty");  
                switches.Add("-dPrinted");  
                switches.Add("-dBATCH");  
                switches.Add("-dNOPAUSE");  
                switches.Add("-dNOSAFER");  
                switches.Add("-dNumCopies=1");  
                switches.Add("-sDEVICE=mswinpr2");  
                switches.Add("-sPAPERSIZE#a4");  
                switches.Add("-dFIXEDMEDIA");  
                switches.Add("-dPDFFitPage");  
                switches.Add("-sOutputFile=%printer%" + defaultPrinter);  
                switches.Add("-f");  
                switches.Add(path);  
                processor.Completed += (object sender, GhostscriptProcessorEventArgs e) => this.printexited(sender, e, path);  
                processor.StartProcessing(switches.ToArray(), null);  
            }  
        }
```

**Comment by jhabjan** [comment]
Can you please attach pdf example that troubles you?

**Comment by dark-cms** [comment]
i will send you an email because the pdf contains company internal data

**Comment by jhabjan** [comment]
Ok, no worries. You can send to habjan@gmail.com. 
Thanks.

**Comment by ChrisKays** [comment]
Hi

I use the print function as @dark-cms but my problem is that i would like to set the Job Name that appear in the print queue at the moment the Job name comes in as "Ghostscript output" i need to change that to a specific name.
From the document i read it says that it can be achieve using command line only, so if that's the case how can i do using c#

**Comment by jhabjan** [comment]
This is not Ghostscript.NET issue, is's more likely native Ghostscript library issue.
