### ISSUE TITLE
Error -100 PDF Marks

### ISSUE THREAD

**Issue by hermesramos** [jhabjan/Ghostscript.NET#32]
Howdy!

I  have tried many, many combinations, but it seems pdf mark is not working.

Here is what I am trying to run:

`var switches = new List<string> 
{ 
"-dBATCH", 
"-dNOPAUSE", 
"-sDEVICE=pdfwrite", 
"-c",
"\"[/Creator()/Author()/Subject()/Title()/Keywords() /DOCINFO pdfmark\"", 
$"-sOutputFile={pdfOutput}", 
pdfInput 
};
`

I always get -100 error.

Thanks in advance

**Comment by Filipowicz251** [comment]
From my experience - error -100 is problem with parameters
in your case i supose -> before pdfInput there should be "-f" parameter

**Comment by vihorlat** [comment]
I have solved my problem with this order of parameters:
```
                    switches = new List<string>();
                    switches.Add("-dPrinted");
                    switches.Add("-dBATCH");
                    switches.Add("-dNOPAUSE");
                    switches.Add("-dNOSAFER");
                    switches.Add("-dNumCopies=1");
                    switches.Add("-sDEVICE=mswinpr2");
                    switches.Add("-sOutputFile=%printer%");
                    switches.Add("-q");
                    switches.Add("-f");
                    switches.Add(tempFilePath);
```
`-f` only worked when `-q` followed `-sOutputFile`
