### ISSUE TITLE
Convert PDF with Arabic font to Image is not working as expected

### ISSUE THREAD

**Issue by ienjreny** [jhabjan/Ghostscript.NET#38]
When we use this library to convert PDF file with Arabic font to image, we got random font in the images, please check the attached sample

![0](https://user-images.githubusercontent.com/19180819/32093739-2e6c88dc-bb06-11e7-8120-e6cb60eca32f.jpg)

**Comment by gilyes** [comment]
Had a similar issue, upgrading Ghostscript to latest (9.22) fixed it for me.

**Comment by ienjreny** [comment]
I upgraded it to 22 but the same issue, please note that we use it from ASP.NET project with https://github.com/jhabjan/Ghostscript.NET, may be the .NET wrapper needs to be updated too!

**Comment by ienjreny** [comment]
I upgraded it to 22 (https://www.ghostscript.com/download/gsdnld.html), but the samee issue, do I have to use version 22 from .NET Lib?

**Comment by jhabjan** [comment]
This is not Ghostscript.NET issue, try to use latest native Ghostscript library.
