### ISSUE TITLE
version 1.2.1 Arithmetic overflow error at DynamicNativeLibrary.FinalizeSections(MEMORY_MODULE* memory_module)

### ISSUE THREAD

**Issue by ahmetmert** [jhabjan/Ghostscript.NET#44]
Hello I have been using GhostScript.net framework for last two weeks and it worked fine till today. I started getting error 

"_Microsoft.WinAny.Interop.DynamicNativeLibrary.FinalizeSections(MEMORY_MODULE* memory_module) at Microsoft.WinAny.Interop.DynamicNativeLibrary.MemoryLoadLibrary(Byte[] data) at Microsoft.WinAny.Interop.DynamicNativeLibrary..ctor(Byte[] buffer) at Ghostscript.NET.GhostscriptLibrary..ctor(GhostscriptVersionInfo version, Boolean fromMemory) at Ghostscript.NET.Processor.GhostscriptProcessor..ctor(GhostscriptVersionInfo version, Boolean fromMemory)_ "

And this is how I call Ghostscprit methods just like shown at example codes.

  GhostscriptVersionInfo gv = GhostscriptVersionInfo.GetLastInstalledVersion();

                using (GhostscriptProcessor processor = new GhostscriptProcessor(gv, true))
                {
                 }

GhostscriptProcessor(gv,true) throws the error above. What makes me worry is that this error persist and ghostscript does not work anymore.
How I can fix this issue ?

**Comment by jhabjan** [comment]
Fixed in today's v.1.2.2. release.
