### ISSUE TITLE
IO error when using reader

### ISSUE THREAD

**Issue by Iwitrag** [jhabjan/Ghostscript.NET#61]
![image](https://user-images.githubusercontent.com/6575704/53913424-9d7e1c00-405b-11e9-9b0b-ac19afce30c0.png)

I'm using GhostScript 9.2.0 64bit with .NET 1.2.1
EDIT: tried GhostScript 9.2.6 - issue not fixed

I get 'IO error for file ... ' when using rasterizer.Open() ...

See image above - first line is string with path
Fourth line is message from exception... as you can see it has some weird characters.

I have tried using ToUtf8String from StringHelper but it didn't work

**Comment by paulohyy** [comment]
I'm having the same issue...

`Ghostscript.NET.GhostscriptException: IO error for file: 'C:\Users\Vin�cius Dutra\AppData\Local\Temp\4c654657-9f51-4858-9fed-0a8b9df56a57.pdf'`

**Comment by KeithVinson** [comment]
Take a look at my issue report here: https://github.com/jhabjan/Ghostscript.NET/issues/64
It may be relevant to your troubles as well. My workaround was to replace all whitespace characters with actual spaces in the file name before passing the file path to ghostscript.  Please realize I mean I had to actually rename the file, not just clean up the path string as passed to Ghostscript.NET.

Hope it might help you

**Comment by AzeExMachina** [comment]
I had the same issue, I got around this by first opening the file as a stream and then passing it to the raster
```csharp
var stream = File.Open(filePath, FileMode.Open);//Or go with using
raster.Open(stream, GhostscriptVersionInfo.GetLastInstalledVersion(GhostscriptLicense.GPL | GhostscriptLicense.AFPL, GhostscriptLicense.GPL), true);
...
stream.Dispose();
```

**Comment by KeithVinson** [comment]
Hi Davide,
Nice find, thanks for updating the community with your work-around.

Keith Vinson
CTO
Image Access, Inc.
543 NW 77th Street, Boca Raton, FL 33487
Tel: 561-886-2951    Fax: 561-431-2766
Keith.Vinson@ImageAccess.com<mailto:Keith.Vinson@ImageAccess.com>

[cid:image001.jpg@01D5D28F.072A59F0]
DLSG is a Division of Image Access, Inc.
www.ImageAccess.com<http://www.imageaccess.com/> / www.DLSG.com<http://www.dlsg.com/>

DLSG is the Most Trusted Name in Digitization for Universities
    ▪ 49 of the top 50 universities are DLSG customers
    ▪ DLSG products serve over 70% of students at US universities

[cid:image002.png@01D5D28F.072A59F0]<https://www.facebook.com/pages/Image-Access-Inc/374428352765764>Visit us on Facebook to see what people are posting about KIC!

**Comment by jhabjan** [comment]
Fixed in today's v.1.2.2. release.
