### ISSUE TITLE
GhostScriptRasterizer shows a PageCount of 0 for all PDFs under GhostScript 9.27

### ISSUE THREAD

**Issue by ryanoshea** [jhabjan/Ghostscript.NET#62]
Package version: 1.21
Ghostscript binary version: 9.27 x64
Platform: Windows 10 1809
Project: ASP.NET on .NET Framework 4.6.1, C#

Running the following code produces a `GhostscriptRasterizer` that has a `PageCount` of `0`.

```csharp
using (var rasterizer = new GhostscriptRasterizer())
{
    rasterizer.Open("<path to file>");
    // rasterizer.PageCount == 0
}
```

The same outcome occurs with any input PDF, regardless of contents. It also occurs when calling the `Stream` overload of `Open()` with a FileStream or MemoryStream.

Downgrading to Ghostscript 9.26 on the same system fixes the issue.

Apologies in advance if 9.27 is not supported by package version 1.21; I couldn't seem to find a compatibility table.

**Comment by himebaugh** [comment]
We ran into the same issue, where `v9.26` works fine, but `v9.27` never finds any pages. We're using a 32 bit compiled version on .NET Framework 4 for building a Windows service.

I suspect that the "tidying" of the Postscript namespace done in `v9.27` may be to blame here. See their [changelog entry](https://www.ghostscript.com/doc/9.27/News.htm#9.27_Incompatible_changes), specifically the "Incompatible changes" section, for more info.

**Comment by voltaek** [comment]
We ran into the same issue, where `v9.26` works fine, but `v9.27` never finds any pages. We're using a 32 bit compiled version on .NET Framework 4 for building a Windows service.

I suspect that the "tidying" of the Postscript namespace done in `v9.27` may be to blame here. See their [changelog entry](https://www.ghostscript.com/doc/9.27/News.htm#9.27_Incompatible_changes), specifically the "Incompatible changes" section, for more info.

**Comment by brianarch82** [comment]
I encountered a similar problem as well. Commenting out the code below seemed to fix the problem. I don't know anything about GhostScript / Postscript otherwise I would try to fix it. 

 // open PDF support dictionaries
            //this.Execute(@"
            //        GS_PDF_ProcSet begin
            //        pdfdict begin");

Please find the changelogs below. 

> 2019-03-19 09:25:48 -0700 
Ray Johnston <ray.johnston@artifex.com>
ebbb3ec7d20b5f4c444eb11fc9835e07229ccbd9

Fix lib/pdf2dsc.ps to use documented Ghostscript pdf procedures.

We eliminated GS_PDF_ProcSet and pdfdict, but runpdfbegin, dopdfpages,
and runpdfend are still available.

lib/pdf2dsc.ps

**Comment by tareq2** [comment]
The same problem. Is there any fix ?

**Comment by deremakif** [comment]
Still same problem!

**Comment by epinox** [comment]
I have a similar problem. I wanted to use the viewer to display a PDF in a form. The events "DisplayUpdate" and "DisplayPage" are not called, only "DisplaySize". It does not work with version 9.52, only up to version 9.26.

**Comment by thienquang07** [comment]
same problem here on Ghostscript version 9.52

**Comment by thienquang07** [comment]
just went back to version 9.26 and it worked fine.

**Comment by JeffOkaki** [comment]
Still a problem and a huge waste of time. Ill try and get a fix submitted. Using GS 9.26 or commenting out the code below works

Ghostscript.NET\Ghostscript.NET\Viewer\FormatHandlers
GhostscriptViewerPdfFormatHandler.cs line 85 through 89

GS_PDF_ProcSet' and 'pdfdict' are private as of GS 9.27

            // open PDF support dictionaries
           // this.Execute(@"
             //       GS_PDF_ProcSet begin
              //      pdfdict begin");
              
https://github.com/mgieseki/dvisvgm/commit/bc51951bc90b700c28ea018993bdb058e5271e9b

seems to have already fixed it in their product.

**Comment by jhabjan** [comment]
Fixed in today's v.1.2.2. release.
