### ISSUE TITLE
Is there a way to point to a folder containing Ghostscript rather than have to install it?

### ISSUE THREAD

**Issue by erotavlas** [jhabjan/Ghostscript.NET#63]
Is there a way to place ghostscript dll's into a folder and point to that folder rather than have to install ghostscript on the machine?  (kind of like the way magick.NET works)

**Comment by jhabjan** [comment]
Yes, take a look at this example: https://github.com/jhabjan/Ghostscript.NET/blob/master/Ghostscript.NET.Samples/Samples/CustomGsdllLocationSample.cs
