### ISSUE TITLE
GhostScript.net Bug  not Recognize special character in fileName

### ISSUE THREAD

**Issue by steiveChina** [jhabjan/Ghostscript.NET#68]
private static string[] GetArgs(string inputFile, string outputFile)
{
    return new[] {
    $"gs",
    $"-o",
    $"{outputFile}",
    $"-dNoOutputFonts",
    $"-sDEVICE=pdfwrite",
    $"{inputFile}",
 }; 

GhostscriptProcessor ghostscript = new GhostscriptProcessor();
string inputFile = "D:\\%你.pdf";（chinese character）
string outputFile = "D:\\%output.pdf";

UTF8Encoding utf8 = new UTF8Encoding();
Byte[] inputFileEncodedBytes = utf8.GetBytes(inputFile);
Byte[] outPutFileEncodedBytes = utf8.GetBytes(outputFile);

string strInput = System.Text.Encoding.UTF8.GetString(inputFileEncodedBytes);
string strOutPut =System.Text.Encoding.UTF8.GetString(outPutFileEncodedBytes);

ghostscript.Process(GetArgs(strInput , strOutPut ));

always give Error  "'gsapi_init_with_args' is made: -100""

**Comment by ygl365166495** [comment]
Support Chinese method:
1.	iapi.h.cs file:
```
public delegate int gsapi_init_with_args(IntPtr instance, Int32 argc, string[] argv); to 
public delegate int gsapi_init_with_args(IntPtr instance, Int32 argc, IntPtr[] argv);
```
2.	StringHelper.cs add:
```
public static IntPtr NativeUtf8FromString(string managedString)
{
int len = Encoding.UTF8.GetByteCount(managedString);
byte[] buffer = new byte[len + 1]; // null-terminator allocated
Encoding.UTF8.GetBytes(managedString, 0, managedString.Length, buffer, 0);
IntPtr nativeUtf8 = Marshal.AllocHGlobal(buffer.Length);
Marshal.Copy(buffer, 0, nativeUtf8, buffer.Length);
return nativeUtf8;
}
```
3.	GhostscriptInterpreter.cs:
```
string[] utf8args = new string[args.Length];
for(int i = 0; i < args.Length; i++)
{
utf8args[i] = StringHelper.ToUtf8String(args[i]);
} 
```
To 
```
IntPtr[] utf8args = new IntPtr[args.Length];
for(int i = 0; i < args.Length; i++)
{
utf8args[i] = StringHelper.NativeUtf8FromString(args[i]);
}
```

**Comment by jhabjan** [comment]
Fixed in today's v.1.2.2. release.
