### ISSUE TITLE
Issue: "An error occured when call to 'gsapi_init_with_args' is made: -100" when converting from PDF to TIFF using .Net Core 2.1

### ISSUE THREAD

**Issue by Luke-Meyer** [jhabjan/Ghostscript.NET#74]
switches.Add("-dNumRenderingThreads=4");
                switches.Add("-q");
                switches.Add("-dSAFER");
                switches.Add("-dBATCH");
                switches.Add("-dNOPAUSE");
                switches.Add("-sDEVICE=tiffg4");
                switches.Add("-sColorConversionStrategy=/LeaveColorUnchanged");
                switches.Add("-sOutputFile=" + convertedFilePath );
                switches.Add(@"-f");
                switches.Add(fileInfo.FullName);

This only happens intermittently.

**Comment by bsebe** [comment]
Maybe not related but I was getting that error code cause to a concurrent call to the library. That showed errors intermittently.
Once I put it into a lock statement it worked like a charm.
Hope it helps you.

**Comment by Luke-Meyer** [comment]
> Maybe not related but I was getting that error code cause to a concurrent call to the library. That showed errors intermittently.
> Once I put it into a lock statement it worked like a charm.
> Hope it helps you.

Thanks for the advice! I will implement a lock on the ghostscript processor and see if that works. Given the low frequency of the issue, however, it may prove difficult to tell if the lock has solved the problem. If encountered again, I will post the news.

**Comment by niwrA** [comment]
When running from a unit test, I always get this same error. Any ideas?

**Comment by bsebe** [comment]
> 
> 
> When running from a unit test, I always get this same error. Any ideas?

The only thing that came to my mind is if you are using the 64 bits dll and the unit test is running on a 32 bit scenario. 
I don't know, but using native dlls usually I always end fighting these kinds of things.

**Comment by jhabjan** [comment]
Can you please try to use latest version of Ghostscript.NET library (v.1.2.3 - released today) and latest version of Ghostscript native library (9.5.3) and see you still have this problem?
