### ISSUE TITLE
x and y dpi ignores the set value

### ISSUE THREAD

**Issue by sarmad99** [jhabjan/Ghostscript.NET#75]
I am using the latest NuGet GhostScript and I am facing this issue:
 ```
             string outputFolder = @"C:\Users";
              string inputFile = @"C:\"
              var xDpi = 300; //set the x DPI
               var yDpi = 300; //set the y DPI
             var pageNumber = 1; // the pages in a PDF document
 (var rasterizer = new GhostscriptRasterizer()) //create an instance for GhostscriptRasterizer
             {
         rasterizer.Open(inputFile); //opens the PDF file for rasterizing

               //set the output image(png's) complete path
          var outputPNGPath = Path.Combine(outputFolder, string.Format("0.png"));

            //converts the PDF pages to png's 
               var pdf2PNG = rasterizer.GetPage(xDpi, yDpi, pageNumber);

               //save the png's
          pdf2PNG.Save(outputPNGPath, ImageFormat.Png);

          Console.WriteLine("Saved " + outputPNGPath);

               }
```
pdf2png vertical and horizontal resolution always default to 96 or 120

**Comment by ummerland** [comment]
I guess this is because the parameters are private in [GhostscriptViewer.cs](https://github.com/jhabjan/Ghostscript.NET/blob/49a233f888eff8d3ac67786a602c5fe40b0da675/Ghostscript.NET/Viewer/GhostscriptViewer.cs)

`        private int _zoom_xDpi = 96;
        private int _zoom_yDpi = 96;`

Strange that there is no error thrown from the debugger

**Comment by ummerland** [comment]
So i made a PR for that, maybe someone can check and validate

**Comment by sarmad99** [comment]
@ummerland  thank you for the replay, late better than never. I made changes to the library a while back and now it is working as it should be I have been meaning to make a pull request to upload the fixed version but been busy. If you want I can email it to you. It works very good

**Comment by ummerland** [comment]
Thanks @sarmad99 for the reply
Oh, that would be great! mastermedia4@gmail.com

After some more investigation i realized that HWResolution in GS is obsolete. So was that the change?

**Comment by jhabjan** [comment]
Fixed in today's v.1.2.2. release.
