### ISSUE TITLE
PDF to image conversion: object transparency/opacity lost

### ISSUE THREAD

**Issue by Todd1561** [jhabjan/Ghostscript.NET#77]
I'm using Ghostscript.NET.Rasterizer to take in a PDF and convert it's pages to individual PNGs.  This works fine but if the source PDF has objects with transparency/opacity less than 100% the resulting image has those objects at 100% opacity, hiding the part of the document underneath.  This does not happen when using GhostScript directly.  I've tried flatting the original PDF before conversion and that did not help.  I'm using GS.Net version 1.2.1 with GS version 9.26

**Comment by YetAnotherDev** [comment]
@Todd1561 i'm not sure if you saw this thread. i havent tried the solution myself but they state it works. I found this post because i'm also having this issue with another library and was looking for an alternative in ghostscript.net. 

https://github.com/jhabjan/Ghostscript.NET/issues/60

**Comment by Todd1561** [comment]
Somehow I missed that, thanks for letting me know.  I have already abandoned GS in favor of buying PDF-Tools by Tracker Software and so far it's been working great in production the last 5 weeks or so.  We use a lot of large architectural drawings with several markup layers and it hasn't had a problem with them yet.

[https://www.tracker-software.com/product/pdf-tools](https://www.tracker-software.com/product/pdf-tools)

**Comment by jhabjan** [comment]
Fixed in today's v.1.2.2. release.
