### ISSUE TITLE
Problems with Ghostscript version 9.53.1

### ISSUE THREAD

**Issue by MAButz** [jhabjan/Ghostscript.NET#81]
Hi, i have update my Ghostscript installation from version 9.22 to 9.53.1 and i'm using Ghostscript.net 1.2.1.

And now i'm using the GhostscriptRasterizer, and after the Update to the 9.53.1 ran into an error.

After a debbuging, i can see that the Ghostscript-API exit with this error: Unable to open the initial device, quitting.

Can anybody confirm this Error?

Thanks a lot.

**Comment by MAButz** [comment]
I have found in the Version-History of Ghostscript 9.52 this entry:

2017-09-19 17:43:25 +0100
Chris Liddell <chris.liddell@artifex.com>
[c49536553df8eef02c6b0fbf1a46eeb2d086859d](http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=c49536553df8eef02c6b0fbf1a46eeb2d086859d)

    Write initial device error to stderr

    As the "Unable to open the initial device, quitting." occurs outside the
    Postscript error handling auspices, and causes Ghostscript to quit in a
    possibly unexpected way, write it to stderr rather than stdout.

    Resource/Init/gs_init.ps

**Comment by fsuk** [comment]
> 
> 
> My last comment ist useless.
> Ghostscript 9.52 work fine with Ghostscript.net 1.2.1.
> 
> The Ghostscript 9.53.1 and higher, will not work with the GhostscriptRasterizer.
> #82 , seem to be the same problem.

I can confirm 9.52 work fine but  Ghostscript 9.53.1 and higher, will not work

**Comment by jhabjan** [comment]
Fixed in today's v.1.2.2. release.

**Comment by jhabjan** [comment]
I just found and fixed this problem earlier today. Will push the changes shortly.

**Comment by MAButz** [comment]
Greate, thanks...
