### ISSUE TITLE
RasterizerSample1 does not work.

### ISSUE THREAD

**Issue by Oninaig** [jhabjan/Ghostscript.NET#82]
Pulling the code and running `RasterizerSample1` from the samples project results it:

```Ghostscript.NET.GhostscriptAPICallException: 'An error occured when call to 'gsapi_init_with_args' is made: -100'```

This is with ghostscript x64 version 9.53.1

**Comment by skartknet** [comment]
Also happening with version x32 9.53.3

**Comment by jhabjan** [comment]
Fixed in today's v.1.2.2. release.
