### ISSUE TITLE
How to capture the bitmap from the ghostscript API?

### ISSUE THREAD

**Issue by joa-quim** [jhabjan/Ghostscript.NET#83]
Hi, pardon from the abuse

This is not a ghostscript.net question but rather a question on how can I capture the raster bitmap resulting from converting a PS file. My question results from the circumstance that I want to use the ghostscript API to convert a PS file and have the result available in memory and not saving it to file (easy). I see that ``Ghostscript.net`` can do it (an image is displayed) but I don't know C# enough to find where that is accomplished. Consulting the Ghostscript docs was not helpful either.

Thank you and Happy New Year.

**Comment by jhabjan** [comment]
This example does exactly what you need: https://github.com/jhabjan/Ghostscript.NET/tree/master/Ghostscript.NET.DisplayTest
