### ISSUE TITLE
GhostscriptRasterizer.GetPage does not rasterize the whole page correctly since v.1.2.2

### ISSUE THREAD

**Issue by asierpn** [jhabjan/Ghostscript.NET#84]
The content of the page is truncated after upgrading to v.1.2.2, with v.1.2.1 itr works perfectly. We use GS 9.26 as a workaround of this issue: https://github.com/jhabjan/Ghostscript.NET/issues/10

**Comment by jhabjan** [comment]
Is it for all your PDF's or specific ones?

**Comment by asierpn** [comment]
I've tested with several and it only happens in some specific ones

**Comment by jhabjan** [comment]
Is there any way you could send me one that doesn't render properly?

**Comment by asierpn** [comment]
I cannot share with you the PDF which is not rasterized correctly because it contains some sensible information, I've tried to create another PDF with the same properties but I've not been able to reproduce the issue with this one.

**Comment by jhabjan** [comment]
Can you try to rasterize that PDF directly with ghostscript (gswin64.exe) and see if the issue is a same?

**Comment by asierpn** [comment]
I've rasterized the PDF directly with ghostscript and the image file is not cropped, I've used this command with both 9.53.3 and 9.26:

`.\gswin64.exe -sDEVICE=jpeg -r300 -dNOPAUSE -dBATCH -sOutputFile="Test.jpg" "Test.pdf"`

**Comment by jhabjan** [comment]
v.1.2.3 that fixes this problem is now rolled out on Github and NuGet. Give it a go and please let me know if this is sorted out now.

**Comment by asierpn** [comment]
I've tested v.1.2.3 and with this version the rasterized page is not being cropped. Thanks.
