### ISSUE TITLE
.Net 4.61: An error occured when call to gsapi_new_instance is made: -100

### ISSUE THREAD

**Issue by joro01** [jhabjan/Ghostscript.NET#85]
Hi,
I've tried to convert a PDF to an image and get the following error:
`Ghostscript.NET.GhostscriptAPICallException: 'An error occured when call to 'gsapi_new_instance' is made: -100'`

I've used you sample code for my implementation. I have not installed Ghostscript on my Computer, I add the gsdll64.dll manually. The Application is a 64bit application, so the assembly 'gs64dll.dll' must be correct .

Can you please help me? Do I have to init an Interpreter first or something like that?

![image](https://user-images.githubusercontent.com/13209067/109799789-b7d43b80-7c1c-11eb-8a6c-392a87b5bf8e.png)

**Comment by jhabjan** [comment]
I just tried that and I can't reproduce the problem. Can you try to run your Visual Studio as Administrator and then try it again?

![ss-jj-41](https://user-images.githubusercontent.com/6780815/109816721-f40d9900-7c28-11eb-8c26-b06117217bd9.png)

**Comment by micke911** [comment]
Hi!
I'm experiencing the same issue trying to  open the rasterizer in a 32 bit .net MVC application. I have installed the Ghostscript.net 1.2.2 package, installed Ghostscript 9.53.3 and copied the gsdll32.dll file to the bin folder.
Running Visual Studio 2019 as Administrator.

```c#                using (var rasterizer = new GhostscriptRasterizer())
                {
                    var dllPath = @"C:\Website\bin\gsdll32.dll";
                    rasterizer.Open(physicalFilePath, new GhostscriptVersionInfo(dllPath), false);
                    var image = rasterizer.GetPage(96, pageNumber);
                 }

**Comment by jhabjan** [comment]
I just found and fixed this problem earlier today.  The changes will be push shortly and I'll publish new dll.

**Comment by jhabjan** [comment]
v.1.2.3 that fixes this problem is now rolled out on Github and NuGet. Give it a go and please let me know if this is sorted out now.

**Comment by joro01** [comment]
Hi, 
I am afraid but it still doesn't work.
Even if I start my VS as admin, it does not work.
I do not have Ghostscript installed on my machine. I just use the assembly . Can this be a problem?

**Comment by micke911** [comment]
Tried Ghostscript.NET v.1.2.3 with Ghostscript 9.53.3 and the exception is not thrown. 
Problem solved for me!

**Comment by jhabjan** [comment]
I'm glad this resolved your issue @micke911
