### ISSUE TITLE
The type or namespace name 'StdIOHandlers' does not exist in the namespace 'Ghostscript.NET.Samples' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by dearwebmaker** [jhabjan/Ghostscript.NET#87]

**Comment by dearwebmaker** [comment]
![image](https://user-images.githubusercontent.com/77912648/111033563-df56af80-8437-11eb-8d11-6292c5f3c33a.png)

**Comment by dearwebmaker** [comment]
How to solve this issue, Please help me

**Comment by jhabjan** [comment]
It looks like the project is missing Ghostscript.NET library reference. Make sure you have Ghostscript.NET under your project references. If not, you can add it from NuGet.

**Comment by dearwebmaker** [comment]
![image](https://user-images.githubusercontent.com/77912648/111035420-82abc280-8440-11eb-89c1-ee630e21fd5f.png)

**Comment by dearwebmaker** [comment]
Hi Habjan
Thanks for your support 
Its working

**Comment by jhabjan** [comment]
Great, I'm glad I could help, Cheers.
