### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by long1000** [jhabjan/Ghostscript.NET#9]
Hi,

I'm using Visual Studio 2013 to open the solution for VS2013 .
But I'm having lots of problem compiling it.
E.g. in streamhelper.cs, it says stream.CopyTo function in line 125, does not contain definition for 'CopyTo'

And many others where the definition cannot be found.
Is there some dependency that I miss?
Thanks.

REgards,
Long

**Comment by andreasblueher** [comment]
Stream.CopyTo Method has been introduced with .NET 4, if you're using anything below it won't work.

**Comment by jhabjan** [comment]
Fixed: https://github.com/jhabjan/Ghostscript.NET/commit/6c74b1e416dea215754c8679fcc1f3caf0b085c3
